### ISSUE TITLE
Architecture discussion on E2E encryption or RTP, HBH RTCP

### ISSUE THREAD

**Issue by paulej** [ietf/perc-wg#102]
It's important to remind implementers that RTCP is not encrypted E2E, so sensitive information that might be placed in SDES items, for example, should not go there.  One might use RFC 7941 as an alternative.

RTP headers can be encrypted E2E, but the values of header extensions need to be negotiated.  Today, they're not negotiated E2E.  We need to address this.

**Comment by fluffy** [comment]
I'm not buying this. If we are going to do video or not has to be agreed end to end but it is not negotiated end to end. The conferences service negotiated it individually with each endpoint / participant.  If the conference requires some feature, and and an endpoint can't do it, either the conference has to re-negoatate with all endpoints to not use the feature or it that participant can't join.

**Comment by paulej** [comment]
Since the extension values are negotiated HBH in PERC, how do we accommodate the desire to allow for E2E encrypted header extensions?  For that matter, how do we even allow non-encrypted header extensions to work?

If Alice says she wants "1=foo", "2=bar", "3=client-audio-level" and Bob says he wants some other combinations of values and extensions, how do we address that?

We could introduce a requirement that the endpoint must use the same extensions IDs as presented in an offer from the media distributor.  That is, allow Alice to send an offer, the media distributor will send an answer. Then require that Alice send a new offer with values that align with what the media distributor suggested to use.

**Comment by suhasHere** [comment]
From the design calls, we concluded that unless there is a strong use-case, PERC will not be doing E2E of RTp Header extensions. I feel we should keep it that way

**Comment by paulej** [comment]
Really? I don't recall that. We know header extensions are needed, though, such as to indicate frame markings, audio levels, etc. While that might be OK for cases where media flows through a single media distributor, that will not allow a cascaded media distributor to properly deal with those types of header extensions.

**Comment by suhasHere** [comment]
I meant to say E2E encryption of the header extensions. However, frame-markings, audio levels are more useful for HbH operation than E2E and I am not sure if there an use-case to encrypt header extensions E2E. Thoughts ?

**Comment by paulej** [comment]
I don't personally have a use-case for those, no. But, we still have to address how we'll get non-encrypted extensions from one media distributor to the next.  The simplest solution, if we can ignore E2E encryption, might be to just replicate them after the OHB. Technically, that might be illegal, but perhaps we allow it for PERC?  We could try to re-negotiate using offer/answer exchanges, though that will get tricky since there is no "master" in the cascaded case.

Perhaps the plan when double was introduced was to replicate those that the media distributors negotiate?  But, there is another issue: what if Alice uses ID=1,2,3, the MD only cares about 2 (but has a different meaning for 2 upstream), but there is some other cascade link down the line that cares about 1.  The meaning between all the hops gets lost.  That's one of the reasons why when we originally did PRIME we allowed the intermediary to modify the RTP header (all of it).  Perhaps for double, we just say that the endpoint must always insert the OHB and media distributors shall only look at RTP header extensions _after_ the OHB?

**Comment by suhasHere** [comment]
I might be missing something .. what happens between MDD to MDD is separate per-hop decision/negotiation and it has nothing to do with EP to MDD negotiation and the values used . For the case above, the MDD will negotiate whatever the MDD<->MDD Offer/Answer rules allow for the extensions they support. This includes OHB as well. If the 2nd MDD doesn't support OHB, the there should be renegotiation at the source to fix it.

**Comment by paulej** [comment]
@suhasHere Take the client to mixer audio level indication as an example.

Say EP1 <=> MD1 negotiate so that MD1 receives this as ID=1.
Say EP2 <=> MD2 negotiates so that MD2 reiceved this as ID=2.

Now, let's say MD1 and MD2 are cascaded.  So, EP1 is sending audio level info as ID=2, but MD1 would like to receive it as ID=2.  (And  we have the opposite for MD2.)

This gets even more complex as we have multiple cascade links (and we do).  MD1 could copy the header extension after the OHB and use the value ID=2 (even though ID=2 might exist before the OHB). The other option is that we have _all_ header extensions after the OHB.

Perhaps the cleanest thing is to do that.  Is there any reason to have header extensions before the OHB?  These cannot be negotiated end-to-end, anyway.

**Comment by fluffy** [comment]
For cases where the options are end to end and the MD can not change the numbers, it seems the conference bridge would do a re-offer to all endpoints  and just set all the end points to use the same number for a given header extension. What am i missing?

**Comment by suhasHere** [comment]
that's my understanding too. (But still we don't have strong use-case for E2E header extensions regardless)

**Comment by nils-ohlmeier** [comment]
For the different ID's on header extensions: who ever runs into that problem needs to generate a new offer to all parties which are not in-sync, to get the IDs to match up (my understanding is that the answerer can't change the ID, it could only reject the extension all together then). It's not easy to implement this logic to get all client onto the same page, but not impossible.

The strongest use case for E2E header extensions I have come up with so far would be a future extension which signs every packet with a private key to prevent identity spoofing. But since such an extension doesn't exist it's not a super strong use case.

The biggest issue though I think is what Sergio is pointing out on the mailing list: how does a client know/learn which header extensions need to go before the OHB and which once after?
Or in other words: which extensions are negotiated HBH with the MDD, and which extensions are E2E?
We don't have any ways to signal/negotiate this so far, or?

**Comment by paulej** [comment]
@fluffy It's more complicated than that.  In a real-world scenario, we might have three servers cascaded like this:

A <=> B <=> C <=> D

There might be any number of endpoints hanging off of those media distribution devices.  If A1 wants to use the ID=1 for some RTP header extension that goes E2E, and client A2 wants to use ID2, and client B1 wants to is ID=4, and client C1 wants to use ID=6, and D1 wants to use ID=7 and D2 wants to use ID=9, it's pretty much impossible to get this resolved through a few offer/answer exchanges. I could see a lot of thrashing and servers stepping on each other trying.  The only way to fix that problem would be to have something central that allocates these identifiers.

**Comment by suhasHere** [comment]
@paulej  even in the cascaded architecture, isn't there a master and slave concept amongst the MCUs and if so shouldn't the master dictate the global state ?

**Comment by paulej** [comment]
No, there's no mater/slave relationship.

Also, I'm wondering if there's a requirement for the endpoint and MD to use the same ID values. When negotiating media flows, the PT value used it directional.  Alice could receive Opus with PT 111 and the MD with PT 99.  I would assume the same is true for header extension values.

**Comment by suhasHere** [comment]
no constraints on using the same ID values or the PT values.

**Comment by paulej** [comment]
So are you suggesting that the answerer dictates IDs to use bidirectionally? That doesn't seem right. Definitely not the way everything else works in SDP.

**Comment by nils-ohlmeier** [comment]
AFAIK answerer can only agree to extension ID's or refuse them, but not choose it's own ID's. And while PT's can be asymetric, they can't for header extension. That's why it should easier for the MD to unify ID's be offering the common ID's for the extensions.

But all of this discussion is pointless as it has been pointed out that we don't have any means to negotiate which extensions are HBH vs E2E. So without that the client has no clue which extensions to put before the OHB and which once after. And I don't think that a signaling extension to cover this is in scope of PERCs agenda. So with that I think we needs to rule out E2E header extensions.

**Comment by paulej** [comment]
So it's even more restrictive than I thought. :)  So, you're saying that the MDD cannot select different values to indicate what it would like to receive.  And the RFC seems to place even more restrictions on what can be re-negotiated.  It would appear that the MDD is not able to change the values used, even with an offer/answer exchange.  The RFC says:

> A session update MAY add or remove extension(s).  Identifiers values in the valid range MUST NOT be altered (remapped).

So if I am reading this right and there are 15 different endpoints, each putting a client to mixer audio level into RTP using a different ID value, then it's going to be virtually impossible for the cascades mixers (in the scenario I mentioned above) to actually convey that information all along the path.

The Media Distributor really needs to be able to change any of the IDs in order to ensure a downstream Media Distributor can understand the meaning of extensions.  So, we either need to not include that part of the RTP header in the initial authenticated encryption or always put extensions after the OHB.

**Comment by suhasHere** [comment]
closing this for now to keep the discussion contianed and revisit after the interim

**Comment by fluffy** [comment]
On the topic of the cascaded ... any cascade design is going to need the cascaded things to coordinate a ton of things. IDs are the least of the issue - they also need to coordinate things like simulcast resolutions and codecs in use. 

So let say a client initial chooses ID 1 for a some extension, but the MD wants it to be 2. The client sends an Offer with 1, the MD sends an answer rejecting it. Now the MD sends a reoffer with 2 and the client accepts it. Note that this is adding a new one with 2, not changing an existing one from 1 to 2.

**Comment by paulej** [comment]
The codec and max bit rate is negotiated. But, we have ways to deal with that.

For this issue, the MD can't just reject the offer since the call is over immediately at that point. The MD would have to accept that offer, but would then be stuck work the offerer's ID values. And any one of dozens of endpoints on the same or different cascade links could do the same.

It's not a huge problem if we just require MDs to rewrite the RTP header extension values.  However, that absolutely rules out E2E extensions with PERC. That's probably ok, too, but then that suggests header extensions should only be added after the OHB.

However, we do need clarification on the RFC. There were definitely two interpretations of "local identifier".
