### ISSUE TITLE
In EKT, fix up msg type, length, spi 

### ISSUE THREAD

**Issue by fluffy** [ietf/perc-wg#12]
1 byte message type : 0 = short, 1 = full
the fully type has a length 
the SPI is 16 bit

**Comment by paulej** [comment]
If I can petition, I'd really like to retain the EKT tag format documented in the last AVTCORE draft (-03).  We have that implemented in libsrtp already in the brach 2_0_0_ekt_dev (https://github.com/cisco/libsrtp/tree/2_0_0_ekt_dev).
