### ISSUE TITLE
Clarify IV formation

### ISSUE THREAD

**Issue by bifurcation** [ietf/perc-wg#128]
The AES-GCM transform generates the IV for a packet from a tuple (SSRC, ROC, SEQ, salt).   

```
                   0  0  0  0  0  0  0  0  0  0  1  1
                   0  1  2  3  4  5  6  7  8  9  0  1
                 +--+--+--+--+--+--+--+--+--+--+--+--+
                 |00|00|    SSRC   |     ROC   | SEQ |---+
                 +--+--+--+--+--+--+--+--+--+--+--+--+   |
                                                         |
                 +--+--+--+--+--+--+--+--+--+--+--+--+   |
                 |         Encryption Salt           |->(+)
                 +--+--+--+--+--+--+--+--+--+--+--+--+   |
                                                         |
                 +--+--+--+--+--+--+--+--+--+--+--+--+   |
                 |       Initialization Vector       |<--+
                 +--+--+--+--+--+--+--+--+--+--+--+--+
```

We need to clarify how this is done for the inner and outer transforms.  In particular:

* Which sequence number is used (original or wire)?
* Are there independent salts?

**Comment by paulej** [comment]
The inner (E2E) should use the SSRC + SEQ in the original RTP packet.  The outer (HBH) should use the values that replace those (if they are changed).  The HBH salt would be different from E2E salt.  The HBH salt comes from the DTLS-SRTP exchange.  The E2E salt comes from the "EKTKey" message sent from the KD.

**Comment by fluffy** [comment]
We should just make it clear that the SSRC, ROC, and SEQ can not be changed.

**Comment by fluffy** [comment]
Whatever needs to be said, it seems how the salt and key are formed it outside double (basically how EKT can replace the full salt/key or just half) but the handling of the bits from the the salt and key string and all the SSRC, ROC, SEQ need to be in double.

**Comment by fluffy** [comment]
Fixed
