### ISSUE TITLE
how to deal with untrusted entities such as announcement servers in the PERC Context

### ISSUE THREAD

**Issue by suhasHere** [ietf/perc-wg#35]

**Comment by fluffy** [comment]
This is related to text that was in framework that said 


- Investigate adding ability to enable the transmission of one-way media
  from a non-trusted device (e.g., announcements). One possible solution
  is to have the Key Distributor send an "ekt_key" message that is explicitly
  labeled for receive-only and giving that to announcement servers.  A
  possible approach would be to define EKT Keys with a SPI > 32000, for
  example, for this purpose and endpoints should only use those EKT Keys
  to decrypt Full EKT Fields received from such transmitters.  Endpoints
  would never send media with EKT Keys with those SPI values.

**Comment by paulej** [comment]
The other solution was to have an explicit indication in the message that delivers the EKT Key to the endpoint of announcement server.  The EKT Key contains the key, cipher, MKI, etc. The KMF could add "direction" as a new field, which would be "send-only" (sent to announcement servers), "receive-only" (sent to endpoints), or "send-receive" for all the "normal" EKT Keys used in the conference between endpoints.  Using SPI values to have certain meaning would work, but the device would have to know its role.  That might lead to some confusion.  So, I'd prefer an explicit indication to the device.  Also, we might want to use this to admit certain endpoints into the conference (e.g., large-scale "webinars" or similar) where endpoints participating should be in listen-only mode.  (Of course, any media they transmit could be discarded, but having a receive-only key makes that more explicit, too.)

**Comment by dabenham** [comment]
Note that at IETF 96, there was no interest in working on this requirement, in part indicating that announcements, etc would come out-of-band and likely not involve media.  The general sentiment was to remove this from the to do list.

**Comment by suhasHere** [comment]
We can close this open issue till there is energy to work on in the WG
