### ISSUE TITLE
Differentiating between EKT and non-EKT sessions with in an end-point?

### ISSUE THREAD

**Issue by suhasHere** [ietf/perc-wg#48]
2.2.2.  Inbound Processing

   When receiving a packet on a RTP stream where EKT was negotiated, the
   following steps are applied for each received packet.

>>> Will an implementation ever be doing SRTP with EKT with some
>>> sessions and SRTP without EKT for other sessions at the same time?
>>> If so, how does the inbound processing determine whether an EKT
>>> is present or not?  Is an additional step needed to perform
>>> "normal SRTP or SRTCP processing" on packets without EKT?

**Comment by fluffy** [comment]
I don't think you can ever receive non EKT packets on a flow with EKT negotiated. That is to say know from the SDP when you get a SRTP packet if it is EKT or not

**Comment by paulej** [comment]
Use of EKT must be negotiated in signalling on a per session basis.  In the case of PERC, all multiplexed flows must use EKT.  For WebRTC, that should also be true, unless a determination can be made based on the payload type.

That actually raises a question.  How are PERC endpoints supposed to construct the SDP for PERC that indicates use of DTLS?  Is that going to be in Adam's draft?  PERC endpoints are always required to initiate the DTLS association.

**Comment by suhasHere** [comment]
Framework and Signaling draft should sum up the usage of this.

**Comment by paulej** [comment]
More reason to delay framework until we know we've covered everything.

**Comment by suhasHere** [comment]
Framework is not getting published anytime soon . We have time :)
