### ISSUE TITLE
When SPI is in use, explain the need for external key management MUST requirement

### ISSUE THREAD

**Issue by suhasHere** [ietf/perc-wg#49]
Section 2.3 Ciphers
EKT uses an authenticated cipher to encrypt and authenticate the
   EKTPlaintext.  We first specify the interface to the cipher, in order
   to abstract the interface away from the details of that function.  We
   then define the cipher that is used in EKT by default.  The default
   cipher described in Section 2.3.1 MUST be implemented, but another
   cipher that conforms to this interface MAY be used, in which case its
   use MUST be coordinated by external means (e.g., key management).

>>> The SPI tells which cipher is being used, so I do not understand the
>>> second MUST in the sentence.  Key management needs to put the key in
>>> place regardless of the algorithm in play.

**Comment by fluffy** [comment]
Fixed by #85
