### ISSUE TITLE
Explain/Clarify padding processing on decryption

### ISSUE THREAD

**Issue by suhasHere** [ietf/perc-wg#50]
Section 2.3

   The decryption function returns a plaintext value P that is at least
   M bytes long, or returns an indication that the decryption operation
   failed because the ciphertext was invalid (i.e. it was not generated
   by the encryption of plaintext with the key K).

>>> It seems that E can pad P.  That is fine.  Why not have D strip
>>> any padding that was put on by E?

   These functions have the property that D(K, E(K, P)) = ( P
   concatenated with optional padding) for all values of K and P.  Each
   cipher also has a limit T on the number of times that it can be used
   with any fixed key value.  The EKTKey MUST NOT be used more that T
   times.

**Comment by fluffy** [comment]
I think the goal was to avoid having a length indicator in the encrypted data as the stuff outside this knows the size (and thus how much pad to remove). Thoughts on what we should say here in the draft ? @suhasHere @paulej

**Comment by suhasHere** [comment]
should we clarify, how the code knows the length of the padding on the decryption side ?

**Comment by paulej** [comment]
I'm unsure what the question is. I reviewed that section of the current draft and it sounds clear. Perhaps the confusion is over the padding?  The AES Key Wrap logic defines how to insert and remove padding.  You can see how that's implemented here: https://github.com/paulej/AESKeyWrap

There is a "with padding" function that inserts required padding per the RFC.

So, what's the question?

**Comment by suhasHere** [comment]
@paul .. I think the question is on clarifying when the padding gets added and removed. Is it out of enc/dec or inside. We might just need to clarify tht

**Comment by paulej** [comment]
It's defined in the RFC. I don't think we should be trying to explain it again here.
