### ISSUE TITLE
TLS1.3 Key and IV Update vs TLS1.2 Content Type (EKTMessage)

### ISSUE THREAD

**Issue by suhasHere** [ietf/perc-wg#57]
Section 4.5.3 of draft-ietf-tls-tls13-18 defined 'Key and IV Update"post handshake message to enable senders to change their cryptographic keys. 

Should ekt-diet use that construct or go ahead with currently defined TLS content type

**Comment by fluffy** [comment]
So after our call last week, I think plan is no change here
