### ISSUE TITLE
EKT Field protection against DOS attacks

### ISSUE THREAD

**Issue by suhasHere** [ietf/perc-wg#59]
Concern:
>>>Based on the DoS security consideration, it appears as if you’re okay 
with the EKT field not be protected by SRTP.  (he asks without having dug into SRTP in a while) 
There’s really no way to get at integrity protection of the EKT field?

**Comment by fluffy** [comment]
So the AESKeyWrap has it's own integrity protection. And the SSRC inside that has to match SRTP to make sure that it applies to the correct one.

**Comment by paulej** [comment]
Yeah.  AES Crypt is self-authenticated by design.
