### ISSUE TITLE
dtls-id reference in the framework

### ISSUE THREAD

**Issue by paulej** [ietf/perc-wg#69]
So I don't forget, if the dtls-id idea is adopted, that draft might go forward as a stand-alone draft, merged into the tunnel spec, or perhaps split (procedures going into tunnel and a skeleton existing only for code point registration).

In all three scenarios, an endpoint developer might not be aware that signaling the dtls-id in SDP would be mandatory.  Thus, we might need some text around that in the framework.

**Comment by fluffy** [comment]
Just updating this bug -  should make the drafts point at tls-id  ?

**Comment by paulej** [comment]
Yeah. Tunnel does now. Framework might not have to.  I put the client requirement into tunnel, but we might want to move that to framework.  Let's discuss the right place.

**Comment by fluffy** [comment]
It seems like this should only be part of tunnel not framework

**Comment by paulej** [comment]
Yeah, endpoint developers are going to have to read the tunnel spec for a few reasons, this being one more.  The text I considered putting into Framework, I just put into the tunnel spec.  So, I will close this issue.
